React
urfu-2020/team-4 pull request #17
Opened 2021-05-15 10:01 UTC by SofiSheromova

Страничка с контактами и с чатом

Пока пр чисто символический, чтобы удобней было посмотреть, если понадобится, поэтому не аппрувте) 
Буду редактировать, когда станет понятно с апи
Если сейчас есть какие-то пожелания или дополнения, то жду комментариев ;)

2021-05-18 07:26 UTC, SofiSheromova commented
Хоть как-то работает

2021-05-19 19:15 UTC, SofiSheromova commented
@Gleb1nho @hariton27sy посмотрите, пожалуйста 
Немного ещё меняла на сервере работу, но без этого бы не вышло
И пока нет подгрузки сообщений

2021-05-20 17:41 UTC, hariton27sy requested changes

2021-05-20 17:41 UTC, hariton27sy commented on config/default.js
> +    staticBasePath: '/public'
Это для девелопа? Или он всегда будет выдавать его из Экспресса? Тип содержимое должно приходить из surge?

2021-05-20 17:44 UTC, SofiSheromova commented on config/default.js
> +    staticBasePath: '/public'
там 2 конфиг файла

2021-05-20 17:44 UTC, SofiSheromova commented on config/default.js
> +    staticBasePath: '/public'
а ещё именно это я сейчас исправляю

2021-05-20 18:54 UTC, SofiSheromova commented on config/default.js
> +    staticBasePath: '/public'
Оно вынужденно переехало в другое место, но там по прежнему в зависимости от NODE_ENV

2021-05-20 19:05 UTC, Gleb1nho approved these changes
Veeeery nice!

2021-05-23 05:55 UTC, hariton27sy approved these changes

2021-06-04 18:26 UTC, merged